### PR TITLE
Update platformio.ini

### PR DESCRIPTION
**Pull request by kristianschneider**

### CODE REVIEW

**Comment by mairas** [comment]
Excellent, thank you!

The GitHub `main` branch can actually be quite unstable at times, so the following would be actually preferable:

```
SignalK/SensESP @ >=3.0.0-beta.6,<4.0.0-alpha.1
```

or simply

```
SignalK/SensESP @ ^3.0.0
```

as soon as v3 is released. I'm just letting the beta6 sit for a bit to see if there are any embarrassing bugs before I hit the button!

**Comment by kristianschneider** [comment]
I still can't compile it though:

`Compiling .pio\build\esp32dev\src\main.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:123:31: error: cannot convert 'std::shared_ptr<sensesp::SensESPMinimalApp>' to 'sensesp::SensESPMinimalApp*' in assignment
                     ->get_app();
                               ^
src/main.cpp:203:56: error: request for member 'get' in 'sensesp_app', which is of pointer type 'sensesp::SensESPMinimalApp*' (maybe you meant to use '->' ?)
   bool display_present = InitializeSSD1306(sensesp_app.get(), &display, i2c);
                                                        ^~~
Archiving .pio\build\esp32dev\lib8fe\libFS.a
In file included from .pio/libdeps/esp32dev/SensESP/src/sensesp/transforms/lambda_transform.h:4,
                 from src/n2k_senders.h:8,
                 from src/main.cpp:19:
.pio/libdeps/esp32dev/SensESP/src/sensesp/ui/config_item.h: In instantiation of 'const String sensesp::ConfigItemT<T>::get_default_config_schema() const [with T = halmet::ADS1115VoltageInput]':
.pio/libdeps/esp32dev/SensESP/src/sensesp/ui/config_item.h:268:16:   required from here
.pio/libdeps/esp32dev/SensESP/src/sensesp/ui/config_item.h:269:33: error: no matching function for call to 'ConfigSchema(std::__shared_ptr_access<halmet::ADS1115VoltageInput, (__gnu_cxx::_Lock_policy)2, false, false>::element_type&)'`

Any thoughts ?

**Comment by mairas** [comment]
Ahh. I understand it now. The example firmware main branch is still against SensESP v2.x. I have updated the code to v3 but I didn't merge it to main branch until I knew things would more or less work.

The beta.6 release doesn't seem to have any showstoppers, so I think I'll merge dev-3 to main in this repo. That will also make this PR redundant.

**Comment by mairas** [comment]
Apologies. I was confused. :-D

**Comment by kristianschneider** [comment]
No worries. I'm glad you are communicating. 
I look forward to test it out

**Comment by mairas** [comment]
I merged the fix in PR #8. That also includes the platformio.ini changes that I had locally but had forgotten to include previously.

**Comment by mairas** [comment]
This PR is now redundant, so closing. Thanks for the heads-up, anyway!

**Comment by kristianschneider** [comment]
Works now. Thanks !

**Pull request closed without merging**
